// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbP_4sR9e1FPl4XgQ6WD7IFim-U0zDBbY',
    appId: '1:399879821078:web:a41f5772fbef6ec91c6237',
    messagingSenderId: '399879821078',
    projectId: 'scoreus-87b8a',
    authDomain: 'scoreus-87b8a.firebaseapp.com',
    storageBucket: 'scoreus-87b8a.appspot.com',
    measurementId: 'G-PHJ1CVXNMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SVDQ_27Eev2AeHZFMyjlBJpHyE-oPQM',
    appId: '1:399879821078:android:9b5324dc6e9ee7491c6237',
    messagingSenderId: '399879821078',
    projectId: 'scoreus-87b8a',
    storageBucket: 'scoreus-87b8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcWDJ6HGOOShhdlsuGgOP3Ntl1ql00sX4',
    appId: '1:399879821078:ios:4365aff5417f012a1c6237',
    messagingSenderId: '399879821078',
    projectId: 'scoreus-87b8a',
    storageBucket: 'scoreus-87b8a.appspot.com',
    androidClientId: '399879821078-9j4e89o3j6t1udajvncn9d18eaqoaj4r.apps.googleusercontent.com',
    iosClientId: '399879821078-sa1kgf4jepd4artjdet4kaa1mu62nqno.apps.googleusercontent.com',
    iosBundleId: 'com.anany.runnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcWDJ6HGOOShhdlsuGgOP3Ntl1ql00sX4',
    appId: '1:399879821078:ios:4365aff5417f012a1c6237',
    messagingSenderId: '399879821078',
    projectId: 'scoreus-87b8a',
    storageBucket: 'scoreus-87b8a.appspot.com',
    androidClientId: '399879821078-9j4e89o3j6t1udajvncn9d18eaqoaj4r.apps.googleusercontent.com',
    iosClientId: '399879821078-sa1kgf4jepd4artjdet4kaa1mu62nqno.apps.googleusercontent.com',
    iosBundleId: 'com.anany.runnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbP_4sR9e1FPl4XgQ6WD7IFim-U0zDBbY',
    appId: '1:399879821078:web:31892e83bcaf66d71c6237',
    messagingSenderId: '399879821078',
    projectId: 'scoreus-87b8a',
    authDomain: 'scoreus-87b8a.firebaseapp.com',
    storageBucket: 'scoreus-87b8a.appspot.com',
    measurementId: 'G-LVDV7TD7MJ',
  );

}