default_platform(:android)

platform :android do
  desc "Lane for android Firebase App Distribution"
  lane :distribute do
    # Clean and build the Flutter APK
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"

    # Firebase App Distribution
    firebase_app_distribution(
      app: "1:399879821078:android:9b5324dc6e9ee7491c6237",
      firebase_cli_token: "1//038AyidR1L9rTCgYIARAAGAMSNwF-L9IrmN9r9r-gXHS2jkS7zi0EbQ8mBwSiqzEKTRHeX1Ez8GLAW_TmCq7mgqhgaYNmNg_pzBc",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk", # Specify the APK path
#         android_artifact_path: "../build/app/outputs/apk/release/app-release.apk", # Updated path

      groups: "active_tester",
      release_notes: "First Abdo Fastlane release"
    )
  end
end
